export const AUDIT_ACTIONS = {
  JOB_CREATED: "JOB_CREATED",
  JOB_STARTED: "JOB_STARTED",
  JOB_RETRY_SCHEDULED: "JOB_RETRY_SCHEDULED",
  JOB_COMPLETED: "JOB_COMPLETED",
  JOB_FAILED: "JOB_FAILED"
} as const;
